//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teretana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clanovi
    {
        static string min = DateTime.Now.ToString();
        static string max = DateTime.Now.AddYears(50).ToString();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clanovi()
        {
            this.AktivnaClanarina = new HashSet<AktivnaClanarina>();
            this.Clanarina = new HashSet<Clanarina>();
            this.DeaktivnaClanarina = new HashSet<DeaktivnaClanarina>();
        }

        public int ClanoviId { get; set; }
        [Required]
        public string Ime { get; set; }
        [Required]
        public string Prezime { get; set; }

        [DataType(DataType.DateTime), Display(Name = "Vreme Od", Description = "-")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yy}", ApplyFormatInEditMode = true)]
        [TimeValidation(ErrorMessage = "Vreme Od mora poceti od sadanjeg datuma.")]
        public System.DateTime VremeOd { get; set; }

        [Time()]
        [DataType(DataType.DateTime), Display(Name = "Vreme Do")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yy}", ApplyFormatInEditMode = true)]
        public System.DateTime VremeDo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnaClanarina> AktivnaClanarina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clanarina> Clanarina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeaktivnaClanarina> DeaktivnaClanarina { get; set; }
    }
}
