//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teretana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanarina
    {
        public int ClanarinaId { get; set; }
        public int ClanoviId { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
    }
}
