//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teretana.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeretanaEntities : DbContext
    {
        public TeretanaEntities()
            : base("name=TeretanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AktivnaClanarina> AktivnaClanarina { get; set; }
        public virtual DbSet<Clanarina> Clanarina { get; set; }
        public virtual DbSet<Clanovi> Clanovi { get; set; }
        public virtual DbSet<DeaktivnaClanarina> DeaktivnaClanarina { get; set; }
    }
}
